# Generated by Django 3.2 on 2024-06-01 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0003_alter_ambulancia_placa'),
    ]

    operations = [
        migrations.AddField(
            model_name='registros',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='registros',
            name='galones',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='correctivo',
            name='foto_factura',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
