# Generated by Django 3.2 on 2024-06-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0007_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(default='M', max_length=10),
        ),
    ]
